# Generated by Django 4.2 on 2025-06-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('coordinator', models.ForeignKey(db_column='coordinator_username', limit_choices_to={'user_type': 'coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_groups', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('mentor', models.ForeignKey(db_column='mentor_username', limit_choices_to={'user_type': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('team', models.ForeignKey(db_column='team_username', limit_choices_to={'user_type': 'team'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'group_details',
            },
        ),
    ]
