# Generated by Django 4.2 on 2025-06-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_groupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mteam',
            fields=[
                ('team', models.OneToOneField(db_column='team_username', limit_choices_to={'user_type': 'team'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mteam_entry', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('coordinator', models.ForeignKey(blank=True, db_column='coordinator_username', limit_choices_to={'user_type': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_teams', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('mentor', models.ForeignKey(blank=True, db_column='mentor_username', limit_choices_to={'user_type': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_teams', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'mteam',
            },
        ),
    ]
