# Generated by Django 4.2 on 2025-06-20 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_mteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('stu_rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('member_name', models.CharField(max_length=30)),
                ('coordinator_marks', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('coordinator', models.ForeignKey(blank=True, db_column='coordinator_username', limit_choices_to={'user_type': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_marks', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('mentor', models.ForeignKey(db_column='mentor_username', limit_choices_to={'user_type': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_marks', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend.team')),
            ],
            options={
                'db_table': 'marks',
            },
        ),
    ]
