# Generated by Django 4.2 on 2025-06-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0004_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_title', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'user_type': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Ttask',
            fields=[
                ('Ttask_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mentor_user', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend.task')),
                ('team_user', models.ForeignKey(limit_choices_to={'user_type': 'team'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ttask',
            },
        ),
    ]
