# Generated by Django 4.2 on 2025-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0007_weeklyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogress',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
