# Generated by Django 4.2 on 2025-07-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0008_weeklyprogress_progress_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
