# Generated by Django 4.2 on 2025-07-04 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0009_alter_marks_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mentor',
            field=models.ForeignKey(blank=True, db_column='mentor_username', limit_choices_to={'user_type': 'mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_marks', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
